version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: school-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: imgmin8689
      MYSQL_DATABASE: school
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

volumes:
  mysql_data: