services:
  # Spring Boot Web Service
  - type: web
    name: international-media-api
    runtime: docker
    plan: free
    region: oregon  # Free tier region
    branch: main
    dockerfilePath: ./Dockerfile
    env:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: "-Xmx450m -Xms200m -XX:+UseG1GC -XX:+UseContainerSupport"
      - key: PORT
        value: "8080"
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:h2:mem:testdb"
      - key: SPRING_DATASOURCE_USERNAME
        value: "sa"
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SPRING_H2_CONSOLE_ENABLED
        value: "true"
      - key: SPRING_H2_CONSOLE_PATH
        value: "/h2-console"
      - key: SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS
        value: "true"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: "create-drop"
      - key: SPRING_JPA_SHOW_SQL
        value: "false"  # Disable SQL logging in production
      - key: LOGGING_LEVEL_ROOT
        value: "INFO"
      - key: LOGGING_LEVEL_COM_HANDONG_INTERNATIONALMEDIA
        value: "INFO"
    buildCommand: ""  # Use Dockerfile
    startCommand: ""  # Use Dockerfile ENTRYPOINT
    healthCheckPath: "/api/members"
    autoDeploy: true
    preDeployCommand: ""
    
    # Free tier resource limits
    disk: 1GB
    
    # Domain configuration (optional)
    # domains:
    #   - international-media-api.onrender.com
    
    # Build and deployment settings
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - ".git/**"
        - "scripts/**"
        - "*.md"
        - ".gitignore"
        - ".dockerignore"
        - "*.http"
        - "*.postman_collection.json"